#!/bin/bash


# the ground truth for wtc-11 wasn't generated by us. we downloaded a ready-to-use VCF file from allen institute.

### https://open.quiltdata.com/b/allencell/tree/aics/wtc11_short_read_genome_sequence/
###  └─variants/
###   └─3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated.vcf.gz




cd /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth


### download the bam file (it's huge!)
wget https://allencell.s3.amazonaws.com/aics/wtc11_short_read_genome_sequence/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.bam

### download the ground-truth vcf file
wget https://allencell.s3.amazonaws.com/aics/wtc11_short_read_genome_sequence/variants/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated.vcf.gz

### index
bcftools index \
  /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated.vcf.gz

### subset only chromosomes chr1, chr2, ..., chr22, chrX, chrY
bcftools view \
  /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated.vcf.gz \
  --regions chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY \
  > /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes.vcf

### compress
bgzip -c /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes.vcf \
  > /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes.vcf.gz
rm /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes.vcf


### filter out non-PASS variants
bcftools view -f PASS \
  /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes.vcf.gz \
  > /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes_pass.vcf

### compress and index
bgzip -c /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes_pass.vcf \
  > /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes_pass.vcf.gz
rm /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes_pass.vcf
bcftools index /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes_pass.vcf.gz
tabix -p vcf /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes_pass.vcf.gz


