#!/bin/bash


# The ground truth for wtc-11 wasn't generated by us. We downloaded a high-quality VCF file from Allen Institute.

### https://open.quiltdata.com/b/allencell/tree/aics/wtc11_short_read_genome_sequence/
###  └─variants/
###   └─3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated.vcf.gz




cd /home/vbarbo/project_2021/paper_analysis/wtc11/ground_truth


### We also download form Allen Institute the BAM file that originated the VCF files
### download the bam file (it's huge!)
wget https://allencell.s3.amazonaws.com/aics/wtc11_short_read_genome_sequence/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.bam

### download the ground-truth vcf file
wget https://allencell.s3.amazonaws.com/aics/wtc11_short_read_genome_sequence/variants/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated.vcf.gz


