#!/bin/bash


# the ground truth for wtc-11 wasn't generated by us. we downloaded a ready-to-use VCF file from allen institute.

### Mark suggested this ground-truth vcf file (slack, July 1):
### https://open.quiltdata.com/b/allencell/tree/aics/wtc11_short_read_genome_sequence/
###  └─variants/
###   └─3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated.vcf.gz


# * fastq files from which the vcf file was generated:
# lane	read_pair	fastq_size
# 2               1          26.7 GB
# 2               2          31.2 GB
# 3               1          26.6 GB
# 3               2          31.5 GB
# 5               1          27.2 GB
# 5               2          31.9 GB
# 6               1          27.8 GB
# 6               2          32.7 GB
#                     TOTAL 235.6 GB


# * bam file from which the vcf file was generated: 452.9 GB



### download the bam file (it's huge!)
wget https://allencell.s3.amazonaws.com/aics/wtc11_short_read_genome_sequence/aligned/84773251_trimmed.AH77TTBBXX_DS-229105_GCCAAT.sorted.rg.final.bam



### download the ground-truth vcf file
cd /home/vbarbo/project_2021/datasets/wtc11/truth/allen_institute_wtc11_shortreads_wgs
wget https://allencell.s3.amazonaws.com/aics/wtc11_short_read_genome_sequence/variants/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated.vcf.gz

### index
bcftools index \
  ~/project_2021/datasets/wtc11/truth/allen_institute_wtc11_shortreads_wgs/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated.vcf.gz

### subset only chromosomes chr1, chr2, ..., chr22, chrX, chrY
bcftools view \
  ~/project_2021/datasets/wtc11/truth/allen_institute_wtc11_shortreads_wgs/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated.vcf.gz \
  --regions chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY \
  > ~/project_2021/datasets/wtc11/truth/allen_institute_wtc11_shortreads_wgs/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes.vcf

### compress
bgzip -c ~/project_2021/datasets/wtc11/truth/allen_institute_wtc11_shortreads_wgs/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes.vcf \
  > ~/project_2021/datasets/wtc11/truth/allen_institute_wtc11_shortreads_wgs/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes.vcf.gz
rm ~/project_2021/datasets/wtc11/truth/allen_institute_wtc11_shortreads_wgs/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes.vcf


### filter out non-PASS variants
bcftools view -f PASS \
  ~/project_2021/datasets/wtc11/truth/allen_institute_wtc11_shortreads_wgs/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes.vcf.gz \
  > ~/project_2021/datasets/wtc11/truth/allen_institute_wtc11_shortreads_wgs/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes_pass.vcf
bgzip -c ~/project_2021/datasets/wtc11/truth/allen_institute_wtc11_shortreads_wgs/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes_pass.vcf \
  > ~/project_2021/datasets/wtc11/truth/allen_institute_wtc11_shortreads_wgs/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes_pass.vcf.gz
rm ~/project_2021/datasets/wtc11/truth/allen_institute_wtc11_shortreads_wgs/3546dc62_AH77TTBBXX_DS-229105_GCCAAT_recalibrated_subsetChromosomes_pass.vcf

