#!/usr/bin/env Rscript


# This script is to fix problematic CIGAR strings of BAM files
# generated by GATK's SplitNCigarReads function. That is, when there 
# are repeated "S" (soft clipping) in a row, merge them. For example, 
# "1000M20S30S" becomes "1000M50S".
# 
# This function may make BAM files suitable for Picard's 
# AddOrReplaceReadGroups
# 
# The input parameters are (following the right order):
# * `INPUT_BAM`, path of the input BAM file;
# * `OUTPUT_BAM`, path of the output BAM file.
#
# To run fixSoftClippingOfBAM:
# Rscript $PATH_TO_REPO/fixSoftClippingOfBAM.r \
#   $INPUT_BAM \
#   $OUTPUT_BAM


### input variables
INPUT_BAM=commandArgs(TRUE)[1]
OUTPUT_BAM=commandArgs(TRUE)[2]


# INPUT_BAM <- "/home/vbarbo/keita/fixCigar/a.bam"
# OUTPUT_BAM <- "/home/vbarbo/keita/fixCigar/fixed_keita.bam"



### test inputs
if( !file.exists(INPUT_BAM) ) stop( gettextf("File %s doesn't exist", INPUT_BAM) )
output_dir <- dirname(OUTPUT_BAM)
if( !dir.exists(output_dir) ) stop( gettextf("Directory %s doesn't exist", output_dir) )

### load packages
suppressPackageStartupMessages( library(Rsamtools) )
suppressPackageStartupMessages( library(GenomicAlignments) )

### load cigar strings
# would it be faster if using bash command: `system(cut -f6 $file", intern=T)`?
cig <- scanBam(INPUT_BAM, param=ScanBamParam(what="cigar")) [[1]] $cigar

### find repeated "S" in a row
cigLetters <- explodeCigarOps(cig)
cigLettersPaste <- sapply(cigLetters, paste, collapse="")
to_fix <- grep("SS", cigLettersPaste)

if( length(to_fix)==0 ){
  cat("There are no CIGAR strings to fix. Lucky you!!!\n")
}else{
  ### create temp dir
  tempDir <- tempfile(pattern="tempDir_", tmpdir=dirname(OUTPUT_BAM))
  cmd <- gettextf("mkdir -p %s", tempDir)
  system(cmd)
  
  ### write sam header
  tempHeader <- tempfile(pattern="tempHeader_", tmpdir=tempDir, fileext=".sam")
  cmd <- gettextf("samtools view -H %s > %s", INPUT_BAM, tempHeader)
  system(cmd)
  
  ### write sam body
  tempSam <- tempfile(pattern="tempSam_", tmpdir=tempDir, fileext=".sam")
  cmd <- gettextf("samtools view %s > %s", INPUT_BAM, tempSam)
  system(cmd)
  
  ### fix cigar strings
  cigLengths <- explodeCigarOpLengths(cig[to_fix])
  pos_to_fix <- gregexpr("(S)\\1{1,}", cigLettersPaste[to_fix])
  
  fixed_cig <- mapply(function(let, len, ptf){
    pos_extended <- NULL
    for(i in seq_along(ptf)){
      ptf_i <- as.integer(ptf)[i]
      ptfLen_i <- attr(ptf, "match.length")[i]
      k <- ptf_i:(ptf_i + ptfLen_i-1)
      len[ k[1] ] <- sum(len[k])
      pos_extended <- c(pos_extended, k[-1])
    }
    let <- let[-pos_extended]
    len <- len[-pos_extended]
    
    paste( c( matrix( c(len, let), nrow=2, byrow=TRUE ) ), collapse="" )
  }, cigLetters[to_fix], cigLengths, pos_to_fix)
  
  # ### save fixed cigar strign to a file
  # # (to save computational time, can I change only the cigar strings (specified by
  # # `to_fix` object) of BAM that needs to be fixed, instead of changing the hole 
  # # column, where correct strings are replaced by the same value?)
  # fixed_cig_file <- tempfile(pattern="fixed_cig_", tmpdir=tempDir, fileext=".txt")
  # write.table(fixed_cig, file=fixed_cig_file, quote=FALSE, row.names=FALSE, col.names=FALSE)
  # ### save index of lines to fix
  # line_indexes_file <- tempfile(pattern="line_indexes_", tmpdir=tempDir, fileext=".txt")
  # write.table(to_fix, file=line_indexes_file, row.names=FALSE, col.names=FALSE)
  
  ### replace the bad cigar strings from the input BAM by the corrected ones, and
  ### save to a file all strings
  cig[to_fix] <- fixed_cig
  all_cig_fixed_file <- tempfile(pattern="all_cig_fixed_", tmpdir=tempDir, fileext=".txt")
  write.table(cig, file=all_cig_fixed_file, quote=FALSE, row.names=FALSE, col.names=FALSE)
  
  ### fix SAM file
  fixed_sam <- tempfile(pattern="fixed_sam_", tmpdir=tempDir, fileext=".sam")
  cmd <- gettextf("awk 'FNR==NR{a[NR]=$1;next}{$6=a[FNR]}1' OFS='\t' %s %s > %s",
                  all_cig_fixed_file, tempSam, fixed_sam)
  system(cmd)
  
  ### add headers to SAN
  fixed_headered_sam_file <- tempfile(pattern="fixed_headered_sam_", tmpdir=tempDir, fileext=".sam")
  cmd <- gettextf("cat %s %s > %s", tempHeader, fixed_sam, fixed_headered_sam_file)
  system(cmd)
  
  ### convert to BAM
  cmd <- gettextf("samtools view -S -b %s > %s", fixed_headered_sam_file, OUTPUT_BAM)
  system(cmd)

  ### delete temp files
  cmd <- gettextf("rm -r %s", tempDir)
  system(cmd)
}

